### PR TITLE
ER diagram

### PR DESCRIPTION
**Pull request by mahdimahdawi**
**This PR Contains:**
- Created schema_based_on_diagram.sql and implemented the database form given diagram.
- Created Join table for many-to-many relationship.
- Created indexes for each FK.

### CODE REVIEW

**Review by thecodechaser — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @mahdimahdawi, and Team👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️



## Required Changes ♻️

- [x] I can't see the database on this PR changes, Please make sure to implement the following as requested in the project requirements.
  -  Please create a file named `schema_based_on_diagram.sql` where you implement the database from the diagram.
  - Please also create join tables from many-to-many relationships.
  - Please remember to add the FK indexes.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by melashu** [comment]
Hello @thecodechaser, thank you so much for your feedback. Would you please give us some context on what we have to do inside `schema_based_on_diagram.sql`? Because we only create a diagram for the existing table.

**Comment by mahdimahdawi** [comment]
**Required Changes Done**

**Review by mukhammadrizooff — APPROVED** [review]
Hi @mahdimahdawi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 

## Optional suggestions
- [ ] [OPTIONAL] It would be better if you put the `schema_based_on_diagram.sql` file in the `README` or `PR` description of the your diagram `image`.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
